### ISSUE TITLE
Create Issue for build failures

### ISSUE THREAD

**Issue by jsg2021** [jenkinsci/pipeline-github-plugin#20]
I'm trying to get my pipelines to create issues for failed builds... is this something that this plugin will support?

**Comment by jsg2021** [comment]
I got it working with the old plugin, but I think it would still be nice to have a 'native' alternative. :)

**Comment by aaronjwhiteside** [comment]
I don't think we'll provide this out of the box, this plugin is supposed to provide a low level programmatic interface to pull requests so that you can build "all the things" you need...

However, I think it would really be useful for everyone to have common problems/scenarios/solutions/approaches/snippets like this documented..

If you are willing to share your approach, I can add it to the `README.md`?

**Comment by jsg2021** [comment]
I put this snippet into a finally block of my scripted pipeline:
```
if (currentBuild.result != 'ABORTED' && "${BRANCH_NAME}" == "master") {
//setup GitHubIssueNotifier
def gitURL = scm.getUserRemoteConfigs()[0].getUrl().replace("git@github.com:","https://github.com/").replace(".git","");
script {
  properties([[$class: 'GithubProjectProperty',
  projectUrlStr: gitURL]])
}

step([$class: 'GitHubIssueNotifier',
  issueAppend: true,
  issueLabel: '',
  issueTitle: '$BRANCH_NAME $BUILD_DISPLAY_NAME failed'])
}
```
