### ISSUE TITLE
multiple issueCommentTriggers in declarative pipeline

### ISSUE THREAD

**Issue by willysamz** [jenkinsci/pipeline-github-plugin#49]
```groovy
pipeline {
    triggers {
      issueCommentTrigger('/deploy')
      issueCommentTrigger('/retest')
    }
}
```
Is it possible to attach multiple issueCommentTriggers in a declarative pipeline? It works in a scripted pipeline but when I try to do something like this in a declarative pipeline I get an error like this:
```
Duplicate trigger name: "issueCommentTrigger"
```

**Comment by willysamz** [comment]
Is this possible in a declarative pipeline?

**Comment by aaronjwhiteside** [comment]
You should use a single trigger with a pattern that matches both use cases..

```groovy
pipeline {
    triggers {
      issueCommentTrigger('/deploy|/retest')
    }
}
```

Note I'm not sure here about needing to escape `/` so YMMV

And a reminder that issueCommentTrigger patterns are regexes... https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html

**Comment by johncblandii** [comment]
Can we reopen this? I think there is a need for a change here.

`/deploy|/retest` is mixing regex here. I can use `|` in the regex so parsing my command to see what command was used becomes a problem.

What I'm trying to do is use the trigger pattern as the regex parser to get all of my groups, etc out of it. If I have a `|` in there (which is a valid regex), it doesn't parse the groups out as expected and I can't split it logically by `|` because there are multiple pipes in each regex.

Example:

```groovy
issueCommentTrigger('/(terraform|helmfile) (.*)\\.(\\S*)\\s?([\\w|-]+).*?|/(custom) (.*)')
```

That supports `/terraform ...` or `/helmfile ...` separately from the `/custom ...`.

I could separate the regex here and simplify it then use my custom regex elsewhere in my script as well. I'm mainly noting here that using `|` as a splitter is problematic to simplifying the regex parsing based on using [IssueCommentClause.triggerPattern](https://github.com/jenkinsci/pipeline-github-plugin/blob/master/src/main/java/org/jenkinsci/plugins/pipeline/github/trigger/IssueCommentCause.java#L19).

Thoughts?
